# Generated by Django 2.0.1 on 2018-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=255, verbose_name='Product type')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Revenue')),
                ('date_sold', models.DateField(verbose_name='Date sold')),
            ],
            options={
                'verbose_name': 'Revenue by goods',
                'db_table': 'revenue',
            },
        ),
    ]
